name: colcon-build
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - galactic

        include:
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
            ros_distribution: galactic
    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ros-tooling/setup-ros@0.3.3
        with:
          required-ros-distributions: galactic

      - name: Build
        uses: ros-tooling/action-ros-ci@0.2.5
        with:
          package-name: ndt_scan_matching 
          target-ros2-distro: galactic
